// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProXamlToolbox
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidProXamlToolboxWindowPackageString = "e3eff216-5897-4190-8950-7cf21985c50e";
        public static Guid guidProXamlToolboxWindowPackage = new Guid(guidProXamlToolboxWindowPackageString);

        public const string guidImagesString = "d7477da6-ccc3-4636-9e71-72434d1d1e3d";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ProXamlToolboxWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}