// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProXamlToolbox
{
    internal sealed partial class Vsix
    {
        public const string Id = "ProXamlToolbox.b9777a55-14f3-4600-adad-13ded99eaadf";
        public const string Name = "Pro XAML Toolbox";
        public const string Description = @"An experimental approach to the faster creation of XAML code in .NET MAUI projects";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Matt Lacey";
        public const string Tags = "XAML;MAUI;DotNetMaui";
    }
}
